import { StyleSheet } from "react-native";
import Constants from "expo-constants";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#6C63FF",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
  },
  InnerContainer: {
    flex: 1,
    backgroundColor: "#FFF",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
    bottom: "5%",
    borderRadius: 16,
    maxHeight:"90%",
  },
  imagem: {
    width: 140,
    height: 140,
    padding: 20,
    marginLeft: -200,
    marginHorizontal: 20,
    borderRadius: 97,
    top:70,
    zIndex:1,
    borderColor:"#6C63FF",
    borderWidth: 1,

  },
  detailsButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginLeft: 250,
    marginTop: -140,
    backgroundColor: "#6C63FF",
    zIndex:1
  },
  detailsButtonText: {
    color: "#6C63FF",
    fontSize: 15,
    fontWeight: "bold",
    zIndex:1
  },
  tituloPerfil: {
    width: "50%",
    height: 40,
    flexDirection: "row",
    borderRadius: 8,
    backgroundColor: "#FFF",
    fontSize: 24,
    color: "#6C63FF",
    fontWeight: "bold",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
    marginTop: 10,
    paddingLeft: 50,
  },
  headerPerfil: {
    borderRadius: 10,
    backgroundColor: "#DADADA",
    marginTop: -65,
    marginLeft:"20%",
    minWidth:"80%",
    minHeight:"17%",
    
  },
  textoPerfil: {
    fontFamily:"Roboto",
    color: "#6C63FF",
    height: 32,
    marginLeft:50,
    fontSize: 14,
    alignSelf: 'center',
    textAlignVertical: "center",
  },
  texto: {
    fontFamily:"Roboto",
    paddingTop:15,
    color: "#6C63FF",
    width: "80%",
    height: 40,
    fontSize: 16,
    fontWeight: "bold",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 8,
  },
  corpo: {
    backgroundColor: "#DADADA",
    borderRadius: 10,
    marginTop: 50,
    minWidth: "100%",
    minHeight: "20%",
  },
  textoCorpo: {
    fontFamily:"Roboto",
    width: "100%",
    height: 35,
    fontSize: 15,
    color: "#252071",
    fontWeight: "bold",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 15,
    paddingVertical: 8,
  },
  comorbidadesCorpo:{
    backgroundColor: "#C4C4C4",
    borderRadius: 10,
    marginTop: 10,
    minWidth: "90%",
    minHeight: "20%",
  },
  detailsFAQButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginLeft: 250,
    marginTop: 30,
    borderRadius: 10,
    borderColor: "#6C63FF",
    width:60,
    borderWidth:1,
    alignItems: "center",
  },
  detailsFAQButtonText: {
    color: "#6C63FF",
    fontSize: 15,
    fontWeight: "bold",
  },
});
